name: aurora_analyzer
description: Package analyzer for Aurora OS
version: 0.1.1
repository: https://github.com/ovc-serega/aurora_analyzer

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  pubspec_parse: ^1.4.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  yaml: ^3.1.3
  json2yaml: ^3.0.1
  meta: ^1.16.0
  cli_table: ^1.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
